config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mystores
  root 'mystores#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :mystores
end

app/models/mystore.rb
class Mystore < ApplicationRecord

  belongs_to :category
  belongs_to :user

  has_attached_file :item_img, styles: {item_index: "250x250>", item_show: "350x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :item_img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :mystores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mystores_controller.rb
class MystoresController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  def index
    if params[:category].blank?
    @items = Mystore.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @items = Mystore.where(:category_id =>  @category_id).order("created_at desc")
      end
  end
  def show

  end

  def new
   @item = current_user.mystores.build
    @categories = Category.all.map{ |c| [c.name, c.id]}

  end

  def create
    @item = current_user.mystores.build(item_params)
    @item.category_id = params[:category_id]
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @item.category_id = params[:category_id]
    if @item.update(item_params)
      redirect_to mystore_path(@item)
  else
    render 'edit'
    end
    end
  def destroy
    @item.destroy
    redirect_to root_path
  end

  private
  def item_params
    params.require(:mystore).permit(:title, :description, :price, :category_id, :item_img)
  end
  def find_item
    @item = Mystore.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mystores_helper.rb
module MystoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "My favorite Store", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li><%= link_to "Sign_out", destroy_user_session_path, method: :delete  %></li>
        <% else %>
            <li><%= link_to "Sign_up", new_user_registration_path %></li>
            <li><%= link_to "Sign_in", new_user_session_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name%>">
                  <%= link_to category.name, mystores_path(category: category.name), class: "link" %>
            <% end %>
            </li>

          </ul>
        </li>

        <% if user_signed_in? %>
            <li><%= link_to "add book", new_mystore_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/mystores/_form.html.erb
<%= simple_form_for @item, :html => {:multipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Selecet a category") %>
    <%= f.file_field :item_img %>
    <%= f.input :title, label: "Назва товару" %>
    <%= f.input :description, label: "Опис" %>
    <%= f.input :price, label: "Ціна"  %>
    <%= f.submit%>
<% end %>

app/views/mystores/edit.html.erb
<h1>Edit Item</h1>
<%= simple_form_for @item, :html => {:multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :item_img %>
    <%= f.input :title, label: "Назва товару" %>
    <%= f.input :description, label: "Опис" %>
    <%= f.input :price, label: "Ціна"  %>
    <%= f.submit%>
<% end %>

app/views/mystores/index.html.erb
<h1 class="current_category"><%= params[:category] %></h1>
<% if @items.count == 0  %>
    <h1>There are no items in this category</h1>
<% else %>

    <div class="row">
      <% @items.each do |item| %>
          <div class="col-md-4">
            <a href="/mystores/<%= item.id %>">
              <%= image_tag item.item_img.url(:item_index), class: "item" %>
            </a>
          </div>

      <% end %>
    </div>

<% end %>

<%= link_to "Додати товар", new_mystore_path %>

app/views/mystores/new.html.erb
<h1>New action</h1>

<%= render 'form' %>

app/views/mystores/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @item.item_img.url(:item_show), class: "item_show"%>
  </div>
  <div class="col-md-8">
    <h2><%= @item.title %></h2>
    <h3><%= @item.price %></h3>
    <p><%= @item.description %></p>
  </div>
  <div class="row">
    <div class="col-md-6">

    </div>
  </div>
</div>
<% if user_signed_in? %>
    <% if @item.user_id == current_user.id %>
        <%= link_to "Edit", edit_mystore_path(@item) %>
        <%= link_to "delete", mystore_path(@item), method: :delete, data: {confirm: "are u sure?"} %>
    <% end %>
<% end %>